### ISSUE TITLE
Deploy on Three Availability Zone

### ISSUE THREAD

**Issue by tonnyadhi** [aws-ia/terraform-aws-polygon-technology-edge#13]
Hello,

I tried to deploy our company private chain Polygon Edge on our local / nearest Region of AWS, which is AWS Jakarta Region (ap-southeast-3). 
Due to government regulation, our fintech service must reside within our country AWS region . Meanwhile, AWS Jakarta Region only have three availablilty zones.

Can we overide the availabilty zones, and deploy 4 nodes with one node overlapping placement inside an availability zone using this terraform ? Or we have to fork the repo and rework it by ourselves. I see that the availability zones number is hardcoded inside this module.

**Comment by sshvans** [comment]
For your specific usecase you need to fork the repo and make necessary changes to the TF module.
