### ISSUE TITLE
Darwin (Mac M1) Not Supported

### ISSUE THREAD

**Issue by aiell0** [aws-ia/terraform-aws-polygon-technology-edge#24]
# Issue Description
When attempting to use this module on a Mac M1 laptop, I get the following error:
```
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
╵
```

This also correlates to the fact that the template provider is [no longer supported](https://registry.terraform.io/providers/hashicorp/template/latest/docs). Another data provider should be used to future proof the module.

**Comment by sshvans** [comment]
Fixed #25
